spring:
  main:
    allow-circular-references: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Microservices
          jwk-set-uri: http://localhost:8080/realms/Microservices/protocol/openid-connect/certs
  datasource:
    url: ${DATABASE_CONNECTION_URL:jdbc:mysql://localhost:3306/angular}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:}
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        jdbc:
          time_zone: UTC
    defer-datasource-initialization: false
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  error:
    include-message: always
  port: 8090
